/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CAPEMON_SCHEMA_PB_H_INCLUDED
#define PB_CAPEMON_SCHEMA_PB_H_INCLUDED
#include "nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _capemon_ArgumentInfo {
    char name[48];
    char type[8];
} capemon_ArgumentInfo;

/* One per API index, emitted the first time that index is logged. Mirrors the
 BSON "info" frame: tells the parser the api name, category and the ordered
 argument names so later CallMessages can be zipped against them. */
typedef struct _capemon_InfoMessage {
    int32_t index;
    char name[64];
    char category[32];
    pb_size_t args_count;
    capemon_ArgumentInfo args[40];
} capemon_InfoMessage;

/* One per hooked API call. `arguments` is positional and lines up 1:1 with
 InfoMessage.args for the same index. is_success / retval are carried in
 dedicated fields (the BSON stream keeps them as args "0" and "1"). */
typedef struct _capemon_CallMessage {
    int32_t index;
    int32_t thread_id;
    uint64_t return_address; /* BSON "R" (main_caller_retaddr) */
    uint64_t parent_return_address; /* BSON "P" (parent_caller_retaddr) */
    bool is_success;
    uint64_t retval;
    pb_callback_t arguments;
    uint64_t timestamp; /* ticks since monitor start (BSON "t") */
    pb_callback_t aux; /* never set by capemon; present for parity */
} capemon_CallMessage;

typedef struct _capemon_ProcessMessage {
    uint64_t timestamp;
    int32_t pid;
    int32_t ppid;
    char module_path[520];
    char proc_name[64];
} capemon_ProcessMessage;

typedef struct _capemon_DebugMessage {
    char message[512];
} capemon_DebugMessage;

typedef struct _capemon_HookEvent {
    pb_size_t which_payload;
    union {
        capemon_InfoMessage info;
        capemon_CallMessage call;
        capemon_ProcessMessage new_process;
        capemon_DebugMessage debug;
    } payload;
} capemon_HookEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define capemon_ArgumentInfo_init_default        {"", ""}
#define capemon_InfoMessage_init_default         {0, "", "", 0, {capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default, capemon_ArgumentInfo_init_default}}
#define capemon_CallMessage_init_default         {0, 0, 0, 0, 0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define capemon_ProcessMessage_init_default      {0, 0, 0, "", ""}
#define capemon_DebugMessage_init_default        {""}
#define capemon_HookEvent_init_default           {0, {capemon_InfoMessage_init_default}}
#define capemon_ArgumentInfo_init_zero           {"", ""}
#define capemon_InfoMessage_init_zero            {0, "", "", 0, {capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero, capemon_ArgumentInfo_init_zero}}
#define capemon_CallMessage_init_zero            {0, 0, 0, 0, 0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define capemon_ProcessMessage_init_zero         {0, 0, 0, "", ""}
#define capemon_DebugMessage_init_zero           {""}
#define capemon_HookEvent_init_zero              {0, {capemon_InfoMessage_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define capemon_ArgumentInfo_name_tag            1
#define capemon_ArgumentInfo_type_tag            2
#define capemon_InfoMessage_index_tag            1
#define capemon_InfoMessage_name_tag             2
#define capemon_InfoMessage_category_tag         3
#define capemon_InfoMessage_args_tag             4
#define capemon_CallMessage_index_tag            1
#define capemon_CallMessage_thread_id_tag        2
#define capemon_CallMessage_return_address_tag   3
#define capemon_CallMessage_parent_return_address_tag 4
#define capemon_CallMessage_is_success_tag       5
#define capemon_CallMessage_retval_tag           6
#define capemon_CallMessage_arguments_tag        7
#define capemon_CallMessage_timestamp_tag        8
#define capemon_CallMessage_aux_tag              9
#define capemon_ProcessMessage_timestamp_tag     1
#define capemon_ProcessMessage_pid_tag           2
#define capemon_ProcessMessage_ppid_tag          3
#define capemon_ProcessMessage_module_path_tag   4
#define capemon_ProcessMessage_proc_name_tag     5
#define capemon_DebugMessage_message_tag         1
#define capemon_HookEvent_info_tag               1
#define capemon_HookEvent_call_tag               2
#define capemon_HookEvent_new_process_tag        3
#define capemon_HookEvent_debug_tag              4

/* Struct field encoding specification for nanopb */
#define capemon_ArgumentInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, STRING,   type,              2)
#define capemon_ArgumentInfo_CALLBACK NULL
#define capemon_ArgumentInfo_DEFAULT NULL

#define capemon_InfoMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    index,             1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, STRING,   category,          3) \
X(a, STATIC,   REPEATED, MESSAGE,  args,              4)
#define capemon_InfoMessage_CALLBACK NULL
#define capemon_InfoMessage_DEFAULT NULL
#define capemon_InfoMessage_args_MSGTYPE capemon_ArgumentInfo

#define capemon_CallMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    index,             1) \
X(a, STATIC,   SINGULAR, INT32,    thread_id,         2) \
X(a, STATIC,   SINGULAR, UINT64,   return_address,    3) \
X(a, STATIC,   SINGULAR, UINT64,   parent_return_address,   4) \
X(a, STATIC,   SINGULAR, BOOL,     is_success,        5) \
X(a, STATIC,   SINGULAR, UINT64,   retval,            6) \
X(a, CALLBACK, REPEATED, BYTES,    arguments,         7) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         8) \
X(a, CALLBACK, REPEATED, BYTES,    aux,               9)
#define capemon_CallMessage_CALLBACK pb_default_field_callback
#define capemon_CallMessage_DEFAULT NULL

#define capemon_ProcessMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, STATIC,   SINGULAR, INT32,    pid,               2) \
X(a, STATIC,   SINGULAR, INT32,    ppid,              3) \
X(a, STATIC,   SINGULAR, STRING,   module_path,       4) \
X(a, STATIC,   SINGULAR, STRING,   proc_name,         5)
#define capemon_ProcessMessage_CALLBACK NULL
#define capemon_ProcessMessage_DEFAULT NULL

#define capemon_DebugMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define capemon_DebugMessage_CALLBACK NULL
#define capemon_DebugMessage_DEFAULT NULL

#define capemon_HookEvent_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,info,payload.info),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,call,payload.call),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,new_process,payload.new_process),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,debug,payload.debug),   4)
#define capemon_HookEvent_CALLBACK NULL
#define capemon_HookEvent_DEFAULT NULL
#define capemon_HookEvent_payload_info_MSGTYPE capemon_InfoMessage
#define capemon_HookEvent_payload_call_MSGTYPE capemon_CallMessage
#define capemon_HookEvent_payload_new_process_MSGTYPE capemon_ProcessMessage
#define capemon_HookEvent_payload_debug_MSGTYPE capemon_DebugMessage

extern const pb_msgdesc_t capemon_ArgumentInfo_msg;
extern const pb_msgdesc_t capemon_InfoMessage_msg;
extern const pb_msgdesc_t capemon_CallMessage_msg;
extern const pb_msgdesc_t capemon_ProcessMessage_msg;
extern const pb_msgdesc_t capemon_DebugMessage_msg;
extern const pb_msgdesc_t capemon_HookEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define capemon_ArgumentInfo_fields &capemon_ArgumentInfo_msg
#define capemon_InfoMessage_fields &capemon_InfoMessage_msg
#define capemon_CallMessage_fields &capemon_CallMessage_msg
#define capemon_ProcessMessage_fields &capemon_ProcessMessage_msg
#define capemon_DebugMessage_fields &capemon_DebugMessage_msg
#define capemon_HookEvent_fields &capemon_HookEvent_msg

/* Maximum encoded size of messages (where known) */
/* capemon_CallMessage_size depends on runtime parameters */
/* capemon_HookEvent_size depends on runtime parameters */
#define CAPEMON_SCHEMA_PB_H_MAX_SIZE             capemon_InfoMessage_size
#define capemon_ArgumentInfo_size                58
#define capemon_DebugMessage_size                514
#define capemon_InfoMessage_size                 2509
#define capemon_ProcessMessage_size              620

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
