/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SCHEMA_PB_H_INCLUDED
#define PB_SCHEMA_PB_H_INCLUDED
#include "nanopb\pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _StrMessage {
    int32_t i;
    pb_callback_t name;
    pb_callback_t type;
    pb_callback_t category;
    pb_callback_t args;
    pb_callback_t api_name;
    pb_callback_t arguments;
} StrMessage;

typedef struct _RegularCall {
    int32_t i;
    int32_t t;
    uint64_t r;
    uint64_t p;
    pb_callback_t c;
    pb_callback_t args;
    pb_callback_t index;
    pb_callback_t aux;
    pb_callback_t data;
} RegularCall;

typedef struct _HookEvent {
    pb_size_t which_message_type;
    union {
        StrMessage str;
        RegularCall regular_call;
    } message_type;
} HookEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define StrMessage_init_default                  {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define RegularCall_init_default                 {0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define HookEvent_init_default                   {0, {StrMessage_init_default}}
#define StrMessage_init_zero                     {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define RegularCall_init_zero                    {0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define HookEvent_init_zero                      {0, {StrMessage_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define StrMessage_i_tag                         1
#define StrMessage_name_tag                      2
#define StrMessage_type_tag                      3
#define StrMessage_category_tag                  4
#define StrMessage_args_tag                      5
#define StrMessage_api_name_tag                  6
#define StrMessage_arguments_tag                 7
#define RegularCall_i_tag                        1
#define RegularCall_t_tag                        2
#define RegularCall_r_tag                        3
#define RegularCall_p_tag                        4
#define RegularCall_c_tag                        5
#define RegularCall_args_tag                     6
#define RegularCall_index_tag                    7
#define RegularCall_aux_tag                      8
#define RegularCall_data_tag                     9
#define HookEvent_str_tag                        1
#define HookEvent_regular_call_tag               2

/* Struct field encoding specification for nanopb */
#define StrMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    i,                 1) \
X(a, CALLBACK, SINGULAR, BYTES,    name,              2) \
X(a, CALLBACK, SINGULAR, BYTES,    type,              3) \
X(a, CALLBACK, SINGULAR, BYTES,    category,          4) \
X(a, CALLBACK, SINGULAR, BYTES,    args,              5) \
X(a, CALLBACK, SINGULAR, BYTES,    api_name,          6) \
X(a, CALLBACK, SINGULAR, BYTES,    arguments,         7)
#define StrMessage_CALLBACK pb_default_field_callback
#define StrMessage_DEFAULT NULL

#define RegularCall_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    i,                 1) \
X(a, STATIC,   SINGULAR, INT32,    t,                 2) \
X(a, STATIC,   SINGULAR, UINT64,   r,                 3) \
X(a, STATIC,   SINGULAR, UINT64,   p,                 4) \
X(a, CALLBACK, SINGULAR, BYTES,    c,                 5) \
X(a, CALLBACK, SINGULAR, BYTES,    args,              6) \
X(a, CALLBACK, SINGULAR, BYTES,    index,             7) \
X(a, CALLBACK, SINGULAR, BYTES,    aux,               8) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              9)
#define RegularCall_CALLBACK pb_default_field_callback
#define RegularCall_DEFAULT NULL

#define HookEvent_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_type,str,message_type.str),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_type,regular_call,message_type.regular_call),   2)
#define HookEvent_CALLBACK NULL
#define HookEvent_DEFAULT NULL
#define HookEvent_message_type_str_MSGTYPE StrMessage
#define HookEvent_message_type_regular_call_MSGTYPE RegularCall

extern const pb_msgdesc_t StrMessage_msg;
extern const pb_msgdesc_t RegularCall_msg;
extern const pb_msgdesc_t HookEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define StrMessage_fields &StrMessage_msg
#define RegularCall_fields &RegularCall_msg
#define HookEvent_fields &HookEvent_msg

/* Maximum encoded size of messages (where known) */
/* StrMessage_size depends on runtime parameters */
/* RegularCall_size depends on runtime parameters */
/* HookEvent_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
