name: MSBuild

on:
  push:
    branches: [ "capemon" ]
  pull_request:
    branches: [ "capemon" ]

env:  
  BUILD_CONFIGURATION: Release
  SOLUTION_FILE_PATH: capemon.sln

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86
            platform: Win32
          - arch: x64
            platform: x64

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with: 
       msbuild-architecture: ${{ matrix.arch }}

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{ matrix.platform }} ${{env.SOLUTION_FILE_PATH}}

    - uses: actions/upload-artifact@v3
      with:
        name: capemon_release_${{ matrix.arch }}
        path: D:\a\capemon\capemon\Release\capemon.dll
        if-no-files-found: ignore
    - uses: actions/upload-artifact@v3
      with:
        name: capemon_release_${{ matrix.arch }}
        path: D:\a\capemon\capemon\x64\Release\capemon_x64.dll
        if-no-files-found: ignore

  publish:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "
        The rolling release triggered on \`${{ github.ref_name }}\`. [View run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
        " > ${{ github.workspace }}-release-body.md

    - uses: actions/download-artifact@v4.1.7

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: rolling
        files: |
         capemon_release_x86/capemon.dll
         capemon_release_x64/capemon_x64.dll
        body_path: ${{ github.workspace }}-release-body.md

    - run: |
        mkdir temp
        mv capemon_release_x86/capemon.dll temp/capemon.dll
        mv capemon_release_x64/capemon_x64.dll temp/capemon_x64.dll

    - name: Push to CAPEv2 repository
      uses: cpina/github-action-push-to-another-repository@v1.4.2
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: temp
        destination-github-username: kevoreilly
        destination-repository-name: capev2
        user-email: action@github.com
        user-name: Github Actions
        target-branch: master
        target-directory: analyzer/windows/dll
